name: Golang CI

on:
  push:
    branches-ignore:
      - main

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Run go test
        run: go test -v ./...

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
